name: crave_workspace

packages:
  - packages/*

scripts:
  analyze:
    run: dart analyze
    description: Run static analysis for all workspace packages.
  test:
    run: melos exec -- dart test
    packageFilters:
      dirExists:
        - test
    description: Run tests only in packages that contain a test directory.
